### ISSUE TITLE
не могу добавить в базу авто

### ISSUE THREAD

**Issue by monstro111111** [duken1111/yii2-test#10]
https://auto.ru/cars/used/sale/lynk_co/08/1121648263-a81aa593/

**Comment by duken1111** [comment]
готово

**Comment by monstro111111** [comment]
https://www.avito.ru/krasnoyarsk/avtomobili/denza_d9_1.5_cvt_2023_10_000_km_3700357608

**Comment by monstro111111** [comment]
https://auto.ru/cars/used/sale/chery/tiggo_8_pro_eplus/1121630536-1af4e834/

**Comment by monstro111111** [comment]
https://www.avito.ru/novosibirsk/avtomobili/venucia_v-online_1.5_amt_2021_27_000_km_3695296682
https://auto.drom.ru/omsk/chery/tiggo_8_pro_e_plus_hybrid/53479482.html
https://www.avito.ru/vladivostok/avtomobili/forthing_t5_evo_1.5_amt_2021_29_000_km_3799894642
https://auto.ru/cars/used/sale/lexus/rz/1122034817-6872b6de/
https://www.avito.ru/krasnoyarsk/avtomobili/rivian_r1s_at_2023_300_km_3799811165

**Comment by monstro111111** [comment]
https://www.avito.ru/samara/avtomobili/livan_x3_pro_1.5_cvt_2023_725_km_3629133776

**Comment by duken1111** [comment]
готово
