### ISSUE TITLE
А комментарии наши в плагине могут исезать?

### ISSUE THREAD

**Issue by monstro111111** [duken1111/yii2-test#19]
несколько раз замечал, что пропадают комментарии к обявлениям

**Comment by duken1111** [comment]
Комментарии могут быть удалены только через раздел https://perekupclub.ru/#/comment и только админами  с ролью admin или root. А так нет возможности больше удалить коммент, только при удалении самого обьявления, но мы их не удаляем

**Comment by monstro111111** [comment]
понял, понаблюдаю
