### ISSUE TITLE
На авито берет криво мотор-коробку-исправить

### ISSUE THREAD

**Issue by monstro111111** [duken1111/yii2-test#2]
![image](https://github.com/duken1111/yii2-test/assets/9220048/b96931cf-e4f9-4098-bf20-139eced0aa37)

**Comment by monstro111111** [comment]
https://www.avito.ru/yablonovskiy/avtomobili/jaguar_xf_3.0_at_2010_245_000_km_2941564510

**Comment by duken1111** [comment]
готово, все параметры парсит корректно

**Comment by monstro111111** [comment]
Некорректно-вариатор парсит как автомат
![image](https://github.com/duken1111/yii2-test/assets/9220048/a0e609cd-cf89-463c-9519-2a3c57af8250)

**Comment by duken1111** [comment]
поправил, должно перепарситься
