### ISSUE TITLE
Почему пишет ошибку, но в базе есть

### ISSUE THREAD

**Issue by monstro111111** [duken1111/yii2-test#23]
https://auto.ru/cars/used/sale/ferrari/812_superfast/1124294857-8f1dd4dc/

**Comment by duken1111** [comment]
Походу ты ошибся с ссылкой, данного авто реально нет в БД

**Comment by monstro111111** [comment]
https://www.avito.ru/yaroslavl/avtomobili/solaris_hs_1.4_mt_2024_10_km_4158194462
https://www.avito.ru/sankt-peterburg/avtomobili/solaris_krx_1.6_at_2024_1_km_4086176637
https://www.avito.ru/voronezh/avtomobili/solaris_hc_1.6_at_2024_10_km_4156440348
![Uploading image.png…]()
тоже в базу добавил а спарсить не могу

**Comment by monstro111111** [comment]
![image](https://github.com/user-attachments/assets/bdf930f1-4d03-4527-b829-9da775182279)

**Comment by duken1111** [comment]
Добавил, не забывай и тут добавлять
![image](https://github.com/user-attachments/assets/e869315a-9fa5-49c2-984c-e77d5d1928c3)
