### ISSUE TITLE
как добавлять в базу такие объявления на авито?

### ISSUE THREAD

**Issue by monstro111111** [duken1111/yii2-test#5]
https://www.avito.ru/lugansk/avtomobili/kia_optima_1.7_amt_2017_225_000_km_3620449619
https://www.avito.ru/kabardino_balkariya_kamenka/avtomobili/hyundai_verna_1.4_mt_2008_240_000_km_3691855577

**Comment by monstro111111** [comment]
https://www.avito.ru/arkhyz/avtomobili/vaz_lada_2114_samara_1.5_mt_2007_190_000_km_3187339841

**Comment by duken1111** [comment]
Доработал парсинг городов по url, если будут попадаться ссылки такие же, кидай сюда, буду добавлять в бд
